#include "STM8S.h"

#define UART_TX GPIOD, GPIO_PIN_5
#define UART_RX GPIOD, GPIO_PIN_6
#define GAIN_A0 GPIOB, GPIO_PIN_4
#define GAIN_A1 GPIOB, GPIO_PIN_5
#define SYNC1   GPIOD, GPIO_PIN_2
#define SYNC2   GPIOA, GPIO_PIN_2
#define SYNC3   GPIOD, GPIO_PIN_3
#define SYNC4   GPIOA, GPIO_PIN_1
#define LED     GPIOA, GPIO_PIN_3

#define SCLK    GPIOC, GPIO_PIN_5
#define DIN     GPIOC, GPIO_PIN_6

#define BAUD_RATE 9600u

main()
{
	char c;

	// init GPIO
	GPIO_Init(GAIN_A0, GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(GAIN_A1, GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SYNC1,   GPIO_MODE_OUT_PP_HIGH_SLOW);
	GPIO_Init(SYNC2,   GPIO_MODE_OUT_PP_HIGH_SLOW);
	GPIO_Init(SYNC3,   GPIO_MODE_OUT_PP_HIGH_SLOW);
	GPIO_Init(SYNC4,   GPIO_MODE_OUT_PP_HIGH_SLOW);
	GPIO_Init(LED,     GPIO_MODE_OUT_PP_HIGH_SLOW);

	// init UART
	GPIO_Init(UART_TX, GPIO_MODE_OUT_PP_HIGH_SLOW);
	GPIO_Init(UART_RX, GPIO_MODE_IN_PU_NO_IT);

	UART1_Init(BAUD_RATE,
						UART1_WORDLENGTH_8D,
						UART1_STOPBITS_1,
						UART1_PARITY_NO,
						UART1_SYNCMODE_CLOCK_DISABLE,
						UART1_MODE_TXRX_ENABLE);
	UART1_Cmd(ENABLE);

	while (1) {
		while (UART1_GetFlagStatus(UART1_FLAG_RXNE) == RESET);
		UART1_ClearFlag(UART1_FLAG_RXNE);

		c = UART1_ReceiveData8();

		if (c == 'b')
			GPIO_WriteReverse(LED);

		UART1_SendData8(c);
	}
}